
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package websfa.soap.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-26T13:31:41.987+02:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "ZTBL_WEBSERVICE",
                      portName = "ZTBL_WEBSERVICE",
                      targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style",
                      wsdlLocation = "file:/D:/Aplicatii/Java/WebSFATest/WebSFATest/WebContent/resources/wsdl/sap_bg_test.wsdl",
                      endpointInterface = "websfa.soap.client.ZTBLWEBSERVICE")
                      
public class ZTBL_WEBSERVICEImpl implements ZTBLWEBSERVICE {

    private static final Logger LOG = Logger.getLogger(ZTBL_WEBSERVICEImpl.class.getName());

    /* (non-Javadoc)
     * @see websfa.soap.client.ZTBLWEBSERVICE#zcalcTrap(java.lang.String vCity, java.lang.String vKunnr, java.math.BigDecimal vNetwr, java.lang.String vRegio, java.lang.String vUl)*
     */
    public java.math.BigDecimal zcalcTrap(java.lang.String vCity, java.lang.String vKunnr, java.math.BigDecimal vNetwr, java.lang.String vRegio, java.lang.String vUl) { 
        LOG.info("Executing operation zcalcTrap");
        System.out.println(vCity);
        System.out.println(vKunnr);
        System.out.println(vNetwr);
        System.out.println(vRegio);
        System.out.println(vUl);
        try {
            java.math.BigDecimal _return = new java.math.BigDecimal("-7309204224131675621.2017654296309910270");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see websfa.soap.client.ZTBLWEBSERVICE#zactDiscMaxim(java.lang.String pattId)*
     */
    public java.lang.String zactDiscMaxim(java.lang.String pattId) { 
        LOG.info("Executing operation zactDiscMaxim");
        System.out.println(pattId);
        try {
            java.lang.String _return = "_return-1119496592";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see websfa.soap.client.ZTBLWEBSERVICE#zcreazaComanda(java.lang.String gvEvent, java.lang.String id, java.lang.String vOk, java.math.BigDecimal vTrans)*
     */
    public void zcreazaComanda(java.lang.String gvEvent, java.lang.String id, javax.xml.ws.Holder<java.lang.String> vOk, javax.xml.ws.Holder<java.math.BigDecimal> vTrans) { 
        LOG.info("Executing operation zcreazaComanda");
        System.out.println(gvEvent);
        System.out.println(id);
        try {
            java.lang.String vOkValue = "vOkValue-602957065";
            vOk.value = vOkValue;
            java.math.BigDecimal vTransValue = new java.math.BigDecimal("-3600284152739870741.7864548796894424608");
            vTrans.value = vTransValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see websfa.soap.client.ZTBLWEBSERVICE#zgetPrice(java.math.BigDecimal gvCant, java.lang.String gvKunnr, java.lang.String gvLgort, java.lang.String gvMatnr, java.lang.String gvSpart, java.lang.String gvVrkme, java.lang.String gvWerks, java.math.BigDecimal gvCantFree, java.lang.String gvCond, java.lang.String gvCurrency, java.lang.String gvMatnrFree, java.math.BigDecimal gvNetwr, java.math.BigDecimal gvNetwrFree, java.math.BigDecimal gvNetwrList, java.lang.String gvNoDisc, java.lang.String gvVrkmeFree, java.math.BigDecimal multiplu, java.math.BigDecimal outCantUmb, java.lang.String outUmb)*
     */
    public void zgetPrice(javax.xml.ws.Holder<java.math.BigDecimal> gvCant, java.lang.String gvKunnr, java.lang.String gvLgort, java.lang.String gvMatnr, java.lang.String gvSpart, javax.xml.ws.Holder<java.lang.String> gvVrkme, java.lang.String gvWerks, javax.xml.ws.Holder<java.math.BigDecimal> gvCantFree, javax.xml.ws.Holder<java.lang.String> gvCond, javax.xml.ws.Holder<java.lang.String> gvCurrency, javax.xml.ws.Holder<java.lang.String> gvMatnrFree, javax.xml.ws.Holder<java.math.BigDecimal> gvNetwr, javax.xml.ws.Holder<java.math.BigDecimal> gvNetwrFree, javax.xml.ws.Holder<java.math.BigDecimal> gvNetwrList, javax.xml.ws.Holder<java.lang.String> gvNoDisc, javax.xml.ws.Holder<java.lang.String> gvVrkmeFree, javax.xml.ws.Holder<java.math.BigDecimal> multiplu, javax.xml.ws.Holder<java.math.BigDecimal> outCantUmb, javax.xml.ws.Holder<java.lang.String> outUmb) { 
        LOG.info("Executing operation zgetPrice");
        System.out.println(gvCant.value);
        System.out.println(gvKunnr);
        System.out.println(gvLgort);
        System.out.println(gvMatnr);
        System.out.println(gvSpart);
        System.out.println(gvVrkme.value);
        System.out.println(gvWerks);
        try {
            java.math.BigDecimal gvCantFreeValue = new java.math.BigDecimal("-1228528849431822894.285576620689657004");
            gvCantFree.value = gvCantFreeValue;
            java.lang.String gvCondValue = "gvCondValue1942081856";
            gvCond.value = gvCondValue;
            java.lang.String gvCurrencyValue = "gvCurrencyValue1879828198";
            gvCurrency.value = gvCurrencyValue;
            java.lang.String gvMatnrFreeValue = "gvMatnrFreeValue1418531915";
            gvMatnrFree.value = gvMatnrFreeValue;
            java.math.BigDecimal gvNetwrValue = new java.math.BigDecimal("8784813188963655277.4346086619274349775");
            gvNetwr.value = gvNetwrValue;
            java.math.BigDecimal gvNetwrFreeValue = new java.math.BigDecimal("1821881897902860243.4499037395757215140");
            gvNetwrFree.value = gvNetwrFreeValue;
            java.math.BigDecimal gvNetwrListValue = new java.math.BigDecimal("208702992854333675.5231358772234683424");
            gvNetwrList.value = gvNetwrListValue;
            java.lang.String gvNoDiscValue = "gvNoDiscValue806319260";
            gvNoDisc.value = gvNoDiscValue;
            java.lang.String gvVrkmeFreeValue = "gvVrkmeFreeValue-247079264";
            gvVrkmeFree.value = gvVrkmeFreeValue;
            java.math.BigDecimal multipluValue = new java.math.BigDecimal("-2724017493266848652.9048267910189703765");
            multiplu.value = multipluValue;
            java.math.BigDecimal outCantUmbValue = new java.math.BigDecimal("6585453218667820423.1115254856489349420");
            outCantUmb.value = outCantUmbValue;
            java.lang.String outUmbValue = "outUmbValue-218214455";
            outUmb.value = outUmbValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see websfa.soap.client.ZTBLWEBSERVICE#zstareComanda(java.lang.String nrCom, java.lang.String pernrCh, java.lang.String stare, java.lang.String vMess, java.lang.String vOk)*
     */
    public void zstareComanda(java.lang.String nrCom, java.lang.String pernrCh, java.lang.String stare, javax.xml.ws.Holder<java.lang.String> vMess, javax.xml.ws.Holder<java.lang.String> vOk) { 
        LOG.info("Executing operation zstareComanda");
        System.out.println(nrCom);
        System.out.println(pernrCh);
        System.out.println(stare);
        try {
            java.lang.String vMessValue = "vMessValue122092605";
            vMess.value = vMessValue;
            java.lang.String vOkValue = "vOkValue-1819292553";
            vOk.value = vOkValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
