package websfa.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-26T13:31:42.002+02:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZTBL_WEBSERVICE")
@XmlSeeAlso({ObjectFactory.class})
public interface ZTBLWEBSERVICE {

    @WebMethod(operationName = "ZcalcTrap", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZTBL_WEBSERVICE:ZcalcTrapRequest")
    @RequestWrapper(localName = "ZcalcTrap", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "websfa.soap.client.ZcalcTrap")
    @ResponseWrapper(localName = "ZcalcTrapResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "websfa.soap.client.ZcalcTrapResponse")
    @WebResult(name = "VTrap", targetNamespace = "")
    public java.math.BigDecimal zcalcTrap(
        @WebParam(name = "VCity", targetNamespace = "")
        java.lang.String vCity,
        @WebParam(name = "VKunnr", targetNamespace = "")
        java.lang.String vKunnr,
        @WebParam(name = "VNetwr", targetNamespace = "")
        java.math.BigDecimal vNetwr,
        @WebParam(name = "VRegio", targetNamespace = "")
        java.lang.String vRegio,
        @WebParam(name = "VUl", targetNamespace = "")
        java.lang.String vUl
    );

    @WebMethod(operationName = "ZactDiscMaxim", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZTBL_WEBSERVICE:ZactDiscMaximRequest")
    @RequestWrapper(localName = "ZactDiscMaxim", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "websfa.soap.client.ZactDiscMaxim")
    @ResponseWrapper(localName = "ZactDiscMaximResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "websfa.soap.client.ZactDiscMaximResponse")
    @WebResult(name = "VOk", targetNamespace = "")
    public java.lang.String zactDiscMaxim(
        @WebParam(name = "PattId", targetNamespace = "")
        java.lang.String pattId
    );

    @WebMethod(operationName = "ZcreazaComanda", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZTBL_WEBSERVICE:ZcreazaComandaRequest")
    @RequestWrapper(localName = "ZcreazaComanda", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "websfa.soap.client.ZcreazaComanda")
    @ResponseWrapper(localName = "ZcreazaComandaResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "websfa.soap.client.ZcreazaComandaResponse")
    public void zcreazaComanda(
        @WebParam(name = "GvEvent", targetNamespace = "")
        java.lang.String gvEvent,
        @WebParam(name = "Id", targetNamespace = "")
        java.lang.String id,
        @WebParam(mode = WebParam.Mode.OUT, name = "VOk", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> vOk,
        @WebParam(mode = WebParam.Mode.OUT, name = "VTrans", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigDecimal> vTrans
    );

    @WebMethod(operationName = "ZgetPrice", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZTBL_WEBSERVICE:ZgetPriceRequest")
    @RequestWrapper(localName = "ZgetPrice", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "websfa.soap.client.ZgetPrice")
    @ResponseWrapper(localName = "ZgetPriceResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "websfa.soap.client.ZgetPriceResponse")
    public void zgetPrice(
        @WebParam(mode = WebParam.Mode.INOUT, name = "GvCant", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigDecimal> gvCant,
        @WebParam(name = "GvKunnr", targetNamespace = "")
        java.lang.String gvKunnr,
        @WebParam(name = "GvLgort", targetNamespace = "")
        java.lang.String gvLgort,
        @WebParam(name = "GvMatnr", targetNamespace = "")
        java.lang.String gvMatnr,
        @WebParam(name = "GvSpart", targetNamespace = "")
        java.lang.String gvSpart,
        @WebParam(mode = WebParam.Mode.INOUT, name = "GvVrkme", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> gvVrkme,
        @WebParam(name = "GvWerks", targetNamespace = "")
        java.lang.String gvWerks,
        @WebParam(mode = WebParam.Mode.OUT, name = "GvCantFree", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigDecimal> gvCantFree,
        @WebParam(mode = WebParam.Mode.OUT, name = "GvCond", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> gvCond,
        @WebParam(mode = WebParam.Mode.OUT, name = "GvCurrency", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> gvCurrency,
        @WebParam(mode = WebParam.Mode.OUT, name = "GvMatnrFree", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> gvMatnrFree,
        @WebParam(mode = WebParam.Mode.OUT, name = "GvNetwr", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigDecimal> gvNetwr,
        @WebParam(mode = WebParam.Mode.OUT, name = "GvNetwrFree", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigDecimal> gvNetwrFree,
        @WebParam(mode = WebParam.Mode.OUT, name = "GvNetwrList", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigDecimal> gvNetwrList,
        @WebParam(mode = WebParam.Mode.OUT, name = "GvNoDisc", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> gvNoDisc,
        @WebParam(mode = WebParam.Mode.OUT, name = "GvVrkmeFree", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> gvVrkmeFree,
        @WebParam(mode = WebParam.Mode.OUT, name = "Multiplu", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigDecimal> multiplu,
        @WebParam(mode = WebParam.Mode.OUT, name = "OutCantUmb", targetNamespace = "")
        javax.xml.ws.Holder<java.math.BigDecimal> outCantUmb,
        @WebParam(mode = WebParam.Mode.OUT, name = "OutUmb", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> outUmb
    );

    @WebMethod(operationName = "ZstareComanda", action = "urn:sap-com:document:sap:soap:functions:mc-style:ZTBL_WEBSERVICE:ZstareComandaRequest")
    @RequestWrapper(localName = "ZstareComanda", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "websfa.soap.client.ZstareComanda")
    @ResponseWrapper(localName = "ZstareComandaResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "websfa.soap.client.ZstareComandaResponse")
    public void zstareComanda(
        @WebParam(name = "NrCom", targetNamespace = "")
        java.lang.String nrCom,
        @WebParam(name = "PernrCh", targetNamespace = "")
        java.lang.String pernrCh,
        @WebParam(name = "Stare", targetNamespace = "")
        java.lang.String stare,
        @WebParam(mode = WebParam.Mode.OUT, name = "VMess", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> vMess,
        @WebParam(mode = WebParam.Mode.OUT, name = "VOk", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> vOk
    );
}
